{% set data = load_setup_py_data() %}

package:
  name: utilities
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python >=3.6

  run:
    - python >=3.6,<3.8
    - numpy >=1.16
    - pandas >=1
    - scipy
    - bokeh >=2.0
    - seaborn >=0.10.0

about:
  home: https://github.com/covid-19-impact-lab/covidlab-utilities
  license: MIT
  license_file: LICENSE
  summary: Package with code that has to be shared across repos of covid-19-impact-lab
